# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import spardha.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(blank=True, null=True, upload_to=spardha.models.get_image_path)),
                ('sex', models.CharField(max_length=1)),
                ('weight', models.IntegerField()),
                ('yearOfStudy', models.IntegerField()),
                ('contact', models.BigIntegerField()),
            ],
        ),
    ]
