# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('eventFor', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='events',
            unique_together=set([('name', 'category', 'eventFor')]),
        ),
    ]
