from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main_page, name='main_page'),
    url(r'^register/', views.register, name='register'),
    url(r'^ourteam/', views.team, name='team'),
    url(r'^confirmation', views.regconfirm, name='confirmation'),
    url(r'^adminlogin', views.adminlogin, name='adminlogin'),
    url(r'^adminfixtures', views.fixturesandresult, name='adminfixtures'),
    url(r'^adminresults', views.results, name='adminresults'),
    url(r'^admin1', views.admin, name='admin'),
    url(r'^login', views.teamlogin, name='teamlogin'),
    url(r'^user', views.user1, name='user'),
    url(r'^adminlogout', views.adminlogout, name='adminlogout'),
    url(r'^logout', views.userlogout, name='logout'),
    url(r'^adminteam', views.ourteam, name='adminteam'),
    url(r'^games', views.usergames, name='usergames'),
    url(r'^adminevents', views.adminevents, name='adminevents'),
    url(r'^college/(?P<num>[0-9]+)/$', views.collegedesc, name='collegedesc'),
    url(r'^events/', views.events, name='events'),
    url(r'^badmintonschedule/', views.badsc, name='badmintonschedule'),
    url(r'^badmintonresult/', views.badres, name='badmintonresult'),
    url(r'^cricketschedule/', views.cricsc, name='cricketschedule'),
    url(r'^cricketresult/', views.cricres, name='cricketresult'),
    url(r'^footballschedule/', views.footballsc, name='footballschedule'),
    url(r'^footballresult/', views.footballres, name='footballresult'),
    url(r'^athleticsschedule/', views.athleticssc, name='athleticsschedule'),
    url(r'^athleticsresult/', views.athleticsres, name='athleticsresult'),
    url(r'^volleyballschedule/', views.volleyballsc, name='volleyballschedule'),
    url(r'^volleyballresult/', views.volleyballres, name='volleyballresult'),
    url(r'^chessschedule/', views.chesssc, name='chessschedule'),
    url(r'^chessresult/', views.chessres, name='chessresult'),
    url(r'^basketballschedule/', views.basketballsc, name='basketballschedule'),
    url(r'^basketballresult/', views.basketballres, name='basketballresult'),
    url(r'^handballschedule/', views.handballsc, name='handballschedule'),
    url(r'^handballresult/', views.handballres, name='handballresult'),
    url(r'^hockeyschedule/', views.hockeysc, name='hockeyschedule'),
    url(r'^hockeyresult/', views.hockeyres, name='hockeyresult'),
    url(r'^khokhoschedule/', views.khokhosc, name='khokhoschedule'),
    url(r'^khokhoresult/', views.khokhores, name='khokhoresult'),
]
